### ISSUE TITLE
Repo path in atom contains a typo - fails to install

### ISSUE THREAD

**Issue by euperia** [rafaelstz/atom-magento-tools#1]
It appears the repository path in atom is incorrect.  Atom attempts to download from https://github.com/rafaelstz/atom-magento-snnipets

**Comment by rafaelstz** [comment]
I can not remove the wrong from my account, that because of the space in the name.
https://atom.io/users/rafaelstz

**Comment by jmargolisvt** [comment]
I'd love to check out the snippets plug in.  But I don't see the github page even with the correct spelling of "snippets".  Did this get rolled into the atom-magento-tools plugin?

**Comment by rafaelstz** [comment]
@jmargolisvt yes, I created **atom-magento-tools** to continue the upgrades, I can't remove and update the other because of your name with space.
